#!/bin/sh

# Use the template for a new email message.
emailAddress='cinnuv@gmail.com'
messageTemplate='/home/pool/message_checkHDD.txt'
message='/tmp/message.txt'
cp $messageTemplate $message
sendMessage="0"
TRIGGER_PATH='/tmp'

# PARAM: $1 = Harddrives
# PARAM: $2 = % disk space full
updateStatus ()
{
	if [ -z "$2" ] ;
	then 
		echo "$1 not mounted!" >> $message
		sendMessage="1"
	elif [ "$2" -ge $limit1 ] && ! [ -e $TRIGGER_PATH/$1.checkHDD_L1 ]; 
	then
		touch $TRIGGER_PATH/$1.checkHDD_L1
		echo "Limit 1 triggered: $1 $2% full" >> $message
		sendMessage="1"
	elif [ "$2" -ge $limit2 ] && ! [ -e $TRIGGER_PATH/$1.checkHDD_L2 ]; 
	then
		touch $TRIGGER_PATH/$1.checkHDD_L2
		echo "Limit 2 triggered: $1 $2% full" >> $message
		sendMessage="1"
	elif [ "$2" -ge $limit3 ] && ! [ -e $TRIGGER_PATH/$1.checkHDD_L3 ]; 
	then
		touch $TRIGGER_PATH/$1.checkHDD_L3
		echo "Limit 3 triggered: $1 $2% full" >> $message
		sendMessage="1"
	elif [ "$2" -ge $limit4 ] && ! [ -e $TRIGGER_PATH/$1.checkHDD_L4 ]; 
	then
		touch $TRIGGER_PATH/$1.checkHDD_L2
		echo "Limit 4 triggered: $1 $2% full" >> $message
		sendMessage="1"
	elif [ "$2" -ge $limit5 ] && ! [ -e $TRIGGER_PATH/$1.checkHDD_L5 ]; 
	then
		touch $TRIGGER_PATH/$1.checkHDD_L5
		echo "Limit 5 triggered: $1 $2% full" >> $message
		sendMessage="1"
	fi
}

# Message we will email (-e gives backslash interpretation)
echo "`date`" >> $message

# Once disk used % crosses these limits, notify user.
limit1=25
limit2=50
limit3=75
limit4=85
limit5=95

# Process all arguments (assumed to be harddrives).
while [ $# -gt 0 ];
do
	hdd=`echo $1 | sed 's/.*\///g'`
	percentFullHDD=`df -h | sed -nr "s/.* ([0-9]{1,2})%.*$hdd$/\1/gp"`
	updateStatus $1 $percentFullHDD
	shift
done

# Send email.
if [ "$sendMessage" = "1" ];
then
	ssmtp $emailAddress < $message
fi 
