#!/bin/sh

# PARAM: $1 = Harddrive, either "HDD1" or "HDD2"
# PARAM: $2 = % disk space full

message='/tmp/checkHDD_msg.txt'

updateStatus ()
{
	if [ -z "$2" ] ;
	then 
		echo "$1 not mounted!"
	elif [ "$2" -ge $limit1 ] && ! [ -e $HOME/$1.checkHDD_L1 ]; 
	then
		touch $HOME/$1.checkHDD_L1
		echo "Limit 1 triggered: $1 $2% full" >> $message
	elif [ "$2" -ge $limit2 ] && ! [ -e $HOME/$1.checkHDD_L2 ]; 
	then
		touch $HOME/$1.checkHDD_L2
		echo "Limit 2 triggered: $1 $2% full" >> $message
	elif [ "$2" -ge $limit3 ] && ! [ -e $HOME/$1.checkHDD_L3 ]; 
	then
		touch $HOME/$1.checkHDD_L3
		echo "Limit 3 triggered: $1 $2% full" >> $message
	elif [ "$2" -ge $limit4 ] && ! [ -e $HOME/$1.checkHDD_L4 ]; 
	then
		touch $HOME/$1.checkHDD_L2
		echo "Limit 4 triggered: $1 $2% full" >> $message
	elif [ "$2" -ge $limit5 ] && ! [ -e $HOME/$1.checkHDD_L5 ]; 
	then
		touch $HOME/$1.checkHDD_L5
		echo "Limit 5 triggered: $1 $2% full" >> $message
	fi
}

#Message we will email
echo "`date`" > $message

# Once disk used % crosses these limits, notify user.
limit1=25
limit2=40
limit3=75
limit4=85
limit5=95


while [ $# -gt 0 ];
do
	hdd=`echo $1 | sed 's/.*\///g'`
	percentFullHDD=`df -h | sed -nr "s/.* ([0-9]{1,2})%.*$hdd$/\1/gp"`
	updateStatus $1 $percentFullHDD
	shift
done
